package storage

import (
	"encoding/json"
	"os"
)

// Notable represents the clean identity block generated by your Python parser
type Notable struct {
	ID      int    `json:"id"`
	Name    string `json:"name"`
	TradeID string `json:"trade_id"`
}

// MemoryDB stores our lookups for ultra-fast, concurrency-safe access
type MemoryDB struct {
	Notables    []Notable
	TradeIDToID map[string]int
}

// LoadNotables ingests the parser's output and indexes it for the Go engine
func LoadNotables(filePath string) (*MemoryDB, error) {
	file, err := os.Open(filePath)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	var list []Notable
	if err := json.NewDecoder(file).Decode(&list); err != nil {
		return nil, err
	}

	tradeMap := make(map[string]int)
	for _, n := range list {
		tradeMap[n.TradeID] = n.ID
	}

	return &MemoryDB{
		Notables:    list,
		TradeIDToID: tradeMap,
	}, nil
}